apiVersion: apps/v1
kind: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.kind }}
metadata:
  name: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.name }}
  labels: 
    {{- with .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.labels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
  annotations:
    {{- with .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.annotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.replicas }}
  
  selector:
    matchLabels:
     {{- with .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.labels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.labels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.service_account }}
      serviceAccountName: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.service_account }}
      {{- end }}
      {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.image_pull_secret }}
      {{- end }}
      {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources }}
      resources:
        {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.limits }}
        limits:
          {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.limits.cpu }}
          cpu: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.limits.cpu }}
          {{- end }}
          {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.limits.memory }}
          memory: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.limits.memory }}
          {{- end }}
        {{- end }}
        {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.requests }}
        requests:
          {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.requests.cpu }}
          cpu: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.requests.cpu }}
          {{- end }}
          {{- if .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.requests.memory }}
          memory: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.resources.requests.memory }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        {{- range .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.volumes }}
        - name: {{ .name }}
          {{- if .secret  }}
          secret:
            secretName: {{ .secret }}
          {{ else if .configmap }}
          configMap:
            name: {{ .configmap }}
          {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.image }}:{{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.image_tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.image_pull_policy }}
          ports:
            - name: http
              containerPort: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.port }}
              protocol: {{ .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.protocol }}
          envFrom:
            {{- range .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.env_from_secret }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.env_from_config }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          volumeMounts:
            {{- range .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.volume_mounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
          env:
          {{- with .Values.helm_workload_2b720787fbad4cb887de31cf51b2404c.env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
