{{- if .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.workload_kind }}
    name: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.workload_name }}
  minReplicas: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_7d247d7bbeed49a6b7d142fa4f5e6436.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}