apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_ef07c4d820884f95b477c1df38d00f16.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_ef07c4d820884f95b477c1df38d00f16.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.helm_service_account_ef07c4d820884f95b477c1df38d00f16.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_ef07c4d820884f95b477c1df38d00f16.automount }}
