{{- if .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.workload_kind }}
    name: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.workload_name }}
  minReplicas: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_10a027d845d242ecb69afcac13543a3d.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}