apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_c3f76e4c9c7444eea878b651c527741a.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_c3f76e4c9c7444eea878b651c527741a.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.helm_service_account_c3f76e4c9c7444eea878b651c527741a.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_c3f76e4c9c7444eea878b651c527741a.automount }}
