helm_hpa_8f46d080f0a34280bd2d8305916d3d5d:
    enabled: true
    max_replicas: 3
    min_replicas: 1
    name: slack-alerts-hpa
    target_cpu_utilization_percentage: 60
    target_memory_utilization_percentage: 70
    workload_kind: Deployment
    workload_name: slack-alerts-workload
helm_ingress_e3e3d50f42044a19b7275a7e864149c7:
    annotations:
        kubernetes.io/ingress.allow-http: "false"
    class_name: nginx
    default_backend_name: slack-alerts-service
    default_backend_port: 80
    enabled: true
    labels:
        service: slack-alerts
    rules: []
    tls: ""
helm_service_account_8b026e788fe445fe9f684d80c67046f5:
    annotations: {}
    automount: false
    labels: {}
    name: testing
helm_service_eb97f1c2bcbd462abefb80a9367426f9:
    name: slack-alerts-service
    port: 80
    protocol: TCP
    selector_labels:
        service: slack-alerts
    target_port: 8000
    type: ClusterIP
helm_workload_51ee90e7ba0444d7aee94255f9214ee0:
    env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/PLACEHOLDER
    env_from_config: []
    env_from_secret: []
    image: ghcr.io/cesar-terraform-modules/retroboard/slack-alerts
    image_pull_policy: Always
    image_pull_secret: null
    image_tag: latest
    kind: Deployment
    labels:
        service: slack-alerts
    name: slack-alerts-workload
    port: 8000
    protocol: TCP
    replicas: 2
    service_account: testing
    volume_mounts: []
    volumes: []
