apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_8b026e788fe445fe9f684d80c67046f5.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_8b026e788fe445fe9f684d80c67046f5.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.helm_service_account_8b026e788fe445fe9f684d80c67046f5.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_8b026e788fe445fe9f684d80c67046f5.automount }}
