helm_hpa_10a027d845d242ecb69afcac13543a3d:
    enabled: true
    max_replicas: 2
    min_replicas: 1
    name: slack-alerts-hpa
    target_cpu_utilization_percentage: 60
    target_memory_utilization_percentage: 60
    workload_kind: Deployment
    workload_name: slack-alerts
helm_ingress_6a7d6ce701564970bdf6a284d45b247e:
    annotations:
        kubernetes.io/ingress.allow-http: "false"
    class_name: nginx
    default_backend_name: slack-alerts
    default_backend_port: 80
    enabled: true
    labels:
        service: slack-alerts
    rules: []
    tls: ""
helm_service_6646de3822294968a133733ebec269f7:
    name: slack-alerts
    port: 80
    protocol: TCP
    selector_labels:
        service: slack-alerts
    target_port: 8000
    type: ClusterIP
helm_service_account_c3f76e4c9c7444eea878b651c527741a:
    annotations: {}
    automount: false
    labels:
        service: slack-alerts
    name: slack-alerts-sa
helm_workload_47fd57af53414d659cc0d386c769922b:
    env:
        PORT: "8000"
    env_from_config: []
    env_from_secret: []
    image: retroboard-slack-alerts
    image_pull_policy: IfNotPresent
    image_pull_secret: null
    image_tag: latest
    kind: Deployment
    labels:
        service: slack-alerts
    name: slack-alerts
    port: 8000
    protocol: TCP
    replicas: 1
    service_account: slack-alerts-sa
    volume_mounts: []
    volumes: []
