apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_99d80fbe277f4eaaaf1cc32d893b2578.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_99d80fbe277f4eaaaf1cc32d893b2578.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.helm_service_account_99d80fbe277f4eaaaf1cc32d893b2578.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_99d80fbe277f4eaaaf1cc32d893b2578.automount }}
