{{- if .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.workload_kind }}
    name: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.workload_name }}
  minReplicas: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_95a1ebd0e71243ec9281cd5689ef3076.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}